#!/bin/bash
# Create placeholder silent MP3 files (1 second of silence)
# This is a minimal valid MP3 file header + silent frame

# Base64 encoded minimal MP3 (short silence ~0.5s)
SILENT_MP3_B64="//uQxAAAAAAAAAAAAAAAAAAAAAAAWGluZwAAAA8AAAACAAADhADAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMD/////////////////////////////////8AAAA8TEFNRTMuMTAwBK8AAAAAAAAAABSAJAYqQQABzAAAg4SXzfVKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/+5DEAAADwABSAAgAAA/g2UEBAAAAAAABAMAAAAEAYPigAADwAAA8AAABgPAAAD/8QBAP/4D/4B/4D4Pz/wEA//8AAAf/4EBwAAAAAH//8B/4Pj//gPB+AAAAAf+AAAH/+A/8AAA//AP+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/7kMQfg8AAAaQAAAAgAAA0gAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"

# Create all voice MP3 files
for voice in alloy ash ballad coral echo sage shimmer verse marin; do
    echo "$SILENT_MP3_B64" | base64 -d > "${voice}.mp3"
    echo "Created ${voice}.mp3"
done

echo "All placeholder MP3 files created!"
